# Generated by xdrgen.py from ../xdr/federation.x on Sat Feb 17 16:20:32 2018
KEY_TYPE_ED25519 = 0
KEY_TYPE_HASH_TX = 1
KEY_TYPE_HASH_X = 2
CryptoKeyType = {
    0 : 'KEY_TYPE_ED25519',
    1 : 'KEY_TYPE_HASH_TX',
    2 : 'KEY_TYPE_HASH_X',
}
PUBLIC_KEY_TYPE_ED25519 = KEY_TYPE_ED25519
PublicKeyType = {
    KEY_TYPE_ED25519 : 'PUBLIC_KEY_TYPE_ED25519',
}
MEMO_NONE = 0
MEMO_TEXT = 1
MEMO_ID = 2
MEMO_HASH = 3
MEMO_RETURN = 4
MemoType = {
    0 : 'MEMO_NONE',
    1 : 'MEMO_TEXT',
    2 : 'MEMO_ID',
    3 : 'MEMO_HASH',
    4 : 'MEMO_RETURN',
}
